### PR TITLE
Bugfixes for creating users / requesting passwords / ...

### PR DESCRIPTION
**Pull request by josvandervelde**
The user list did not get updated, because only a single SqlAlchemy session was used. This lead to "user not found" errors when retrieving a user with a token. E.g. creating a new user, requesting a new password, ...

It probably broke after updating SQLAlchemy version. Currently, it is not recommended to work with a single session (it might have never been recommended). Changed into explicitely creating a `Session`, using a `sessionmaker`.

### CODE REVIEW

**Comment by josvandervelde** [comment]
I already deployed this to production, to make sure people can sign up again.
I did this by changing to this branch on the prod server.

**Comment by joaquinvanschoren** [comment]
Well done! Thanks!

Joaquin Vanschoren, Ph.D., ir.
Associate Professor
Department of Mathematics and Computer Science
Eindhoven University of Technology (TU/e)
https://joaquinvanschoren.github.io/

**Comment by josvandervelde** [comment]
I've added some additional bugfixes to this PR, to make sure uploading datasets through the frontend works.

I've deployed the fix and it works! Just uploaded a new dataset.

There is a slight change in functionality, I think. Now the license has a default value: Public Domain (CC0). Previously, I think it was blank by default. I think this is fine - every dataset should have a license, and this CC0 makes sense by default. Thoughts?
See https://www.openml.org/auth/upload-dataset

**Review by joaquinvanschoren — APPROVED** [review]
Nicely done! Great session management!

**Pull request merged**
